spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springSecurity?createDatabaseIfNotExist=true
    username: root
    password: Ku77imaa0231@
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
